CREATE TABLE `tmp_retail_data` (
  `customer_id` int DEFAULT NULL,
  `age` int DEFAULT NULL,
  `gender` text,
  `income_bracket` text,
  `loyalty_program` text,
  `membership_years` int DEFAULT NULL,
  `churned` text,
  `marital_status` text,
  `number_of_children` int DEFAULT NULL,
  `education_level` text,
  `occupation` text,
  `transaction_id` int DEFAULT NULL,
  `transaction_date` text,
  `product_id` int DEFAULT NULL,
  `product_category` text,
  `quantity` int DEFAULT NULL,
  `unit_price` double DEFAULT NULL,
  `discount_applied` double DEFAULT NULL,
  `payment_method` text,
  `store_location` text,
  `transaction_hour` int DEFAULT NULL,
  `day_of_week` text,
  `week_of_year` int DEFAULT NULL,
  `month_of_year` int DEFAULT NULL,
  `avg_purchase_value` double DEFAULT NULL,
  `purchase_frequency` text,
  `last_purchase_date` text,
  `avg_discount_used` double DEFAULT NULL,
  `preferred_store` text,
  `online_purchases` int DEFAULT NULL,
  `in_store_purchases` int DEFAULT NULL,
  `avg_items_per_transaction` double DEFAULT NULL,
  `avg_transaction_value` double DEFAULT NULL,
  `total_returned_items` int DEFAULT NULL,
  `total_returned_value` double DEFAULT NULL,
  `total_sales` double DEFAULT NULL,
  `total_transactions` int DEFAULT NULL,
  `total_items_purchased` int DEFAULT NULL,
  `total_discounts_received` double DEFAULT NULL,
  `avg_spent_per_category` double DEFAULT NULL,
  `max_single_purchase_value` double DEFAULT NULL,
  `min_single_purchase_value` double DEFAULT NULL,
  `product_name` text,
  `product_brand` text,
  `product_rating` double DEFAULT NULL,
  `product_review_count` int DEFAULT NULL,
  `product_stock` int DEFAULT NULL,
  `product_return_rate` double DEFAULT NULL,
  `product_size` text,
  `product_weight` double DEFAULT NULL,
  `product_color` text,
  `product_material` text,
  `product_manufacture_date` text,
  `product_expiry_date` text,
  `product_shelf_life` int DEFAULT NULL,
  `promotion_id` int DEFAULT NULL,
  `promotion_type` text,
  `promotion_start_date` text,
  `promotion_end_date` text,
  `promotion_effectiveness` text,
  `promotion_channel` text,
  `promotion_target_audience` text,
  `customer_zip_code` int DEFAULT NULL,
  `customer_city` text,
  `customer_state` text,
  `store_zip_code` int DEFAULT NULL,
  `store_city` text,
  `store_state` text,
  `distance_to_store` double DEFAULT NULL,
  `holiday_season` text,
  `season` text,
  `weekend` text,
  `customer_support_calls` int DEFAULT NULL,
  `email_subscriptions` text,
  `app_usage` text,
  `website_visits` int DEFAULT NULL,
  `social_media_engagement` text,
  `days_since_last_purchase` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
